app01/models.py
from django.db import models
import datetime
#from app03_sales.models import Payment,Customer

# Create your models here.
class Students(models.Model):
    stu_name = models.CharField(max_length=32)
    stu_account = models.CharField(max_length=32)
    stu_password = models.CharField(max_length=32) 
    #和学生详情一对一，建在查询频率高的表
    stu_detail = models.OneToOneField(to='Stu_detail',on_delete=models.CASCADE)
    regi_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.stu_name

class Stu_detail(models.Model):
    tel = models.CharField(max_length=32,null=True)##integer可能会超限
    addr = models.CharField(max_length=32,null=True)
    school = models.CharField(max_length=32,null=True)
    birthday = models.DateField()
    class_count = models.IntegerField(verbose_name="已上课时")
    class_remain = models.IntegerField(verbose_name="剩余课时")
    class_left = models.IntegerField(verbose_name="缺课次数")
    class_price = models.IntegerField(verbose_name="课程金额")
    #一对多：models.ForeignKey(to="xxxx")，建在多的一方，to少的一方
    ## 学生和教师多对多，orm外键字段键在任意一方均可，一般在使用频率高的表，不需要再创一张表
    #teacher是虚拟字段，告诉orm创建一个多对多关系
    #teachers = models.ManyToManyField(to='Teachers')
    #classes = models.ManyToManyField(to='Classes')
    #classes_process = models.ManyToManyField(to='Class_bkp')


class Salers(models.Model):
    sale_name = models.CharField(max_length=32,default='cc')
    sale_account = models.CharField(max_length=32,unique=True)
    sale_password = models.CharField(max_length=32)
    if_admin = models.BooleanField(default=False)
    ## 小数总共4位，小数点后2位
    regi_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.sale_name


class Teachers(models.Model):
    tch_name = models.CharField(max_length=32)
    tch_account = models.CharField(max_length=32,unique=True)
    tch_password = models.CharField(max_length=32)
    ## 小数总共4位，小数点后2位
    regi_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.tch_name

class Files(models.Model):
    uploader = models.ForeignKey(to='Teachers',to_field='tch_account',on_delete= models.CASCADE,verbose_name='上传用户',related_name='上传用户')
    ## 给avatar字段传文件对象 该文件会自动存储到avatar文件下，然后avatar字段只保存文件路径
    files = models.FileField(upload_to='files/',verbose_name='上传文件')
    #size = models.CharField(max_length=16)
    cc = models.ForeignKey(to='Teachers',verbose_name='抄送人',to_field='tch_account',on_delete= models.CASCADE,related_name='抄送人',null=True,blank=True)
    verify_person = models.ForeignKey(to='Teachers',to_field='tch_account',verbose_name='审核人',on_delete= models.CASCADE,related_name='审核人',null=True,blank=True)
    if_verify = models.CharField(max_length=10,default='0')
    ## 0：未审核
    verify_mode = models.CharField(max_length=10,default='0')
    notes = models.TextField(blank=True,null=True,verbose_name='文件备注')
    create_time = models.DateField(auto_now_add=True)

class Outline(models.Model):
    cid=models.IntegerField(verbose_name='编号')
    uploader = models.ForeignKey(to='Teachers',to_field='tch_account',on_delete= models.CASCADE,verbose_name='上传用户',related_name='上传教师')
    ## 给avatar字段传文件对象 该文件会自动存储到avatar文件下，然后avatar字段只保存文件路径
    files = models.FileField(upload_to='outline/',verbose_name='上传文件')
    #size = models.CharField(max_length=16)
    category = models.ForeignKey(to='Class_category',on_delete= models.CASCADE,verbose_name='课程分类')
    theme = models.CharField(max_length=32,verbose_name='上课主题')
    description = models.TextField(blank=True,null=True,verbose_name='课程描述')
    notes = models.TextField(blank=True,null=True,verbose_name='文件备注')
    create_time = models.DateField(auto_now_add=True)

class Class_category(models.Model):
    name = models.CharField(max_length=32,verbose_name='课程分类')
    def __str__(self):
        return self.name

class Classes(models.Model):
    cid = models.CharField(max_length=10,verbose_name='课程编号')
    class_name = models.CharField(max_length=32)
    class_category = models.CharField(max_length=32)
    if_end = models.BooleanField(default=False)
    class_count = models.IntegerField(verbose_name="已上课时",default=0)
    def __str__(self):
        return self.class_name

class Classrooms(models.Model):
    classroom_name = models.CharField(max_length=32,default='未分配')
    campus = models.CharField(max_length=32,default='未分配')
    resource = models.CharField(max_length=16,default=None)
    def __str__(self):
        return self.classroom_name
    
class Schedules(models.Model):
    class_name = models.ForeignKey(to='Classes',on_delete= models.CASCADE,verbose_name='班级')
    class_room = models.ForeignKey(to='Classrooms',on_delete= models.CASCADE,verbose_name='教室')
    class_teacher = models.ForeignKey(to='Teachers',on_delete= models.CASCADE)
    classes = models.IntegerField(verbose_name='课时')
    beginning = models.DateTimeField()
    ending = models.DateTimeField()
    notes = models.TextField(verbose_name='备注',blank=True,null=True)
    status = models.BooleanField(verbose_name='已完成',default=False)
    regi_date = models.DateField(auto_now_add=True)

class Transcations(models.Model):
    consultor = models.CharField(max_length=32)


class Class_bkp(models.Model):
    '''
    学生A报B课情况
    '''
    stu_name = models.ForeignKey(to='Stu_detail',on_delete= models.CASCADE)
    classes_name = models.ManyToManyField(to='Classes')
    tches_name =  models.ManyToManyField(to='Teachers')
    if_end = models.BooleanField(default=False)
    #class_count = models.IntegerField(verbose_name="已上课时")
    create_time = models.DateField(auto_now=True)
    '''
    relate_payment = models.ManyToManyField(to='app03_sales.Payment')
    
    class_remain = models.IntegerField(verbose_name="剩余课时")
    class_left = models.IntegerField(verbose_name="缺课次数")
    class_price = models.IntegerField(verbose_name="课程金额")
    '''


class Salary(models.Model):
    tch = models.ForeignKey(to="Teachers", on_delete=models.CASCADE)
    class_price = models.IntegerField(verbose_name="课时费",null=True,blank=True)
    other_price = models.IntegerField(verbose_name="其他收入",null=True,blank=True)
    expenditure = models.IntegerField(verbose_name="支出",null=True,blank=True)
    month = models.DateField(verbose_name="月份")
    create_time = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return datetime.datetime.strftime(self.month,"%Y-%m-%d")
        

templates/article_detail.html
{% extends "site_base.html" %}

{% block content %}
<!-- 左侧文章区 start -->
<div class="col-md-9 container-fluid " style="word-wrap: break-word;">
            <div class="panel panel-default">
            <div class="panel-heading">
            <h1>{{article_obj.title}}</h1>
            </div>
            <div class="panel-body text-left" style="min-height:200px" >
                {{article_obj.content|safe}}
            </div>
            
            <div class="panel-footer">
                <span class="action VoteButton--up">
                    <button aria-label="赞同" type="button" class="Button VoteButton VoteButton--up" id='voteup'>
                    <div class="glyphicon glyphicon-thumbs-up" style="display: inline-flex; align-items: center;"></div>
                    &nbsp;赞同 &nbsp;<span id="voteup_num"> {{ article_obj.up_num}}</span></button>
            </span>
            <span class="action">
            <button aria-label="反对" type="button" class="Button VoteButton VoteButton--down" id='votedown'>
            <div class="glyphicon glyphicon-thumbs-down" style="display: inline-flex; align-items: center;"></div>
            &nbsp;反对 &nbsp;<span id="votedown_num">{{ article_obj.down_num}}</span></button>
            </span>
            <div id='clicktips' style='color:red'></div>
            </div>
            
            
</div><!--col-md-8-->
<!-- 评论楼 start-->
<div>
<p class="glyphicon glyphicon-th-large">评论区</p>
<ul class="list-group" id="comment-group">
    {% if comment_list %}
        {% for comment in comment_list%}
            <li class="list-group-item" style="height:35px">
            <span style="font-weight:bold"> #{{ forloop.counter }}楼</span>
            <span> {{ comment.comment_time|date:'Y-m-d H:i:s' }}&nbsp;&nbsp;</span>
            <span class="glyphicon glyphicon-user"><a href="/Cshow/{{comment.user.username}}/" > {{ comment.user.username }}</a></span>
            <span> <a class="pull-right reply" username="{{comment.user.username}}" comment_id="{{comment.pk}}">回复</a></span>
            </li>
            <li class="list-group-item">
            <!-- 判断子评论 -->
            {% if comment.parent_id %}
                <p style="color:gray"><cite>引用：@ {{comment.parent.user.username}} </cite></p>
                <p style="color:gray"><cite>&nbsp;{{comment.parent.content}}</cite>
                </p>
                <hr>
            {% endif %}
            {{ comment.content}}
            </li>
        {% endfor %}
    {% else %}
        <li class="list-group-item" style="height:100px">
            <p> 您的文章暂无评论 </p>
        </li>
    {% endif %}

</ul>
</div>
<!-- 评论楼 end-->


<!-- 文章评论样式 start-->
{% if request.user.is_authenticated %}
<div>
    <p><span class="glyphicon glyphicon-comment">发表评论</p>
    <div>
        <textarea name="comment" id="id_comment" cols="60" rows="10"></textarea>
    </div>
    <button class="btn btn-default" id='submit_comment'>提交评论</button>
</div>
{% else %}
    <p> 请先注册或登录再进行评论</p>
        <li><a href="{% url 'register'%}">注册</a></li>
        <li><a href="{% url 'login'%}">登录</a></li>
{% endif %}
<!-- 文章评论样式 end-->
</div> 
<!-- 左侧文章区 end-->
{% endblock %}

{% block js %}

<script>
 // 设置全局的parentID字段
 let parentId = null;
 //给所有action类绑定
  $('.action').click(function(){
      let isUP = $(this).hasClass('VoteButton--up');
      let $btn = $(this);
      // 发送ajax请求
      $.ajax({
          url:"/Cshow/up_and_down/",
          type:"POST",
          data:{
              "article_id":"{{article_obj.pk}}",
              "is_up":isUP,
              "csrfmiddlewaretoken":"{{csrf_token}}"
          },
          success:function(args){
            
            if (args.code == 1000){
                $('#clicktips').text(args.msg)
                // 将前端数字+1
                // 1. 先获取之前的数字
                if (isUP){
                    var num = Number($('#voteup_num').text());
                    $('#voteup_num').text(num+1)
                }
                else{
                    var num = Number($('#votedown_num').text());
                    $('#votedown_num').text(num+1)}
            } 
            else{
                $('#clicktips').html(args.msg)
                /*
                if (isUP){
                    var num = Number($('#voteup_num').text());
                    $('#voteup_num').text(num+1)
                }
                else{
                    var num = Number($('#votedown_num').text());
                    $('#votedown_num').text(num+1)}
                    */
            }
          }
      
  })
  })
// 根评论
 $('#submit_comment').click(function(){
     // 1. 获取评论内容
    let conTent =  $('#id_comment').val();
    // 2. 判断是不是子评论
    if (parentId){
        let indexNum = conTent.indexOf('\n')+1;
        conTent = conTent.slice(indexNum);
    }
    $.ajax({
        url:'/Cshow/comment/',
        type: 'POST',
        data:{
            // 2. 给哪篇文章评论
            'article_id':'{{article_obj.pk}}',
            // 3. 评论内容
            'content': conTent,
            // 4. 评论人
            'csrfmiddlewaretoken':'{{csrf_token}}',
            'parent_id': parentId
        },
        success:function(args){
            if (args.code == 1000){
                // 1. 清除评论框内容
                $('#id_comment').val('');
                // 2. 临时渲染
                let userName = '{{ request.user.username }}';
                let temp = '<li class="list-group-item" style="height:10px, width:300px"> <span> ${userName} </span> <span> <a href="" class="pull right">回复</a></span> </li> <li class="list-group-item"> ${conTent} </li>';
                alert(temp);
                // 3.将生成的标签加入ul
                $('#comment-group').append(temp);
                // 4. 清除全局的parentid
                parentId = null;
            }
        }
    })
 })


 // 子评论
 // 给回复按钮绑定点击事件
 $('.reply').click(function(){
     // 评论人
    let commentUserName = $(this).attr('username');
     // 评论主键值 (全局)
    parentId = $(this).attr('comment_id');
    $('#id_comment').val('@'+commentUserName+'\n').focus()
 })
</script>

{% load static %}
<script charset="utf-8" src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script>
            KindEditor.ready(function(K) {
                    window.editor = K.create('#id_comment',
                   { width : '70%', 
                   height : '300px',
                   resizeType : '1',
                   uploadJson : '/upload_image/',
                   extraFileUploadParams:{ 'csrfmiddlewaretoken':'{{csrf_token}}'},
                   items:[
        '|', 'undo', 'redo', '|', 'preview', 'print', 'template', 'code', 'cut', 'copy', 'paste',
        'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
        'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
        'superscript', 'clearhtml', 'quickformat', 'selectall', '|', '/',
        'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
        'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat', '|', 'image', 'multiimage',
        'flash', 'media', 'insertfile', 'table', 'hr', 'emoticons', 'baidumap', 'pagebreak',
        'anchor', 'link', 'unlink', '|', 'about']
        });
                   })
    </script>
{% endblock %}

templates/eduadmin_class.html
<!-- 继承模板 -->
{% extends 'home.html' %}



{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
    <h3 class="panel-title">班级管理</h3>
    </div>
</div>
<div class="row">
   <div class="col-lg-6">
        <div class="input-group">
            <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">学生姓名 <span class="caret"></span></button>
                <ul class="dropdown-menu">
                <li><a href="#">班级名</a></li>
                <li><a href="#">教师</a></li>
                <li><a href="#">教室</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                </ul>
            </div><!-- /btn-group -->
            <input type="text" class="form-control" aria-label="请输入查找内容">
            
            <span class="input-group-btn">
            <button type="button" class="btn btn-default" aria-haspopup="true" aria-expanded="false">查找</button>
            </span>
             </div><!-- /.col-lg-6 -->
             <div class="btn-group-btn ">
            <span class="input-group-addon">
                <input type="radio" name="header_checkbox" aria-label="done" id="done" class="header_checkbox">已结课
            </span>
            <span class="input-group-addon">
                <input  type="radio" name="header_checkbox" aria-label="doing" id="doing" class="header_checkbox">未结课
            </span>
            
            <span class="input-group-addon">
                    <input type="radio" name="header_checkbox" aria-label="none" id="none" class="header_checkbox">未排课
            </span>

            <span class="input-group-addon">
            <input type="radio" name="header_checkbox" aria-label="none" id="reset" class="header_checkbox">重置
            </span>
        </div><!-- /input-group -->
</div><!-- /.row -->
<div class="row">
 
  <div class="btn-group-btn">
            <a href="{% url 'stu_add' %}" class="btn btn-info ">添加</a>
            <a href="" class="btn btn-warning">发送消息</a>
            <a href="" class="btn btn-success">导出Excel</a>
             <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    更多操作 <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#" >导入名单</a></li>
    <li><a href="#">导出名单</a></li>
  </ul>
        </div><!-- /btn-group -->
</div><!-- /.row -->
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th> 班级名称</th>
                <th> 授课类型</th>
                <th> 授课时段</th>
                <th> 授课教师</th>
                <th> 人数</th>
                <th> 已消耗课时</th>
                <th> 操作 </th>
            </tr>
        </thead>
        <tbody>
            {% for stu in class_list %}
                <tr>
                   <!--
                    <td>
                    {% for c in stu.tches_name.all%}
                        {% if forloop.last %}
                            {{c.tch_name}}
                            {% else %}
                            {{c.tch_name}},
                        {% endif %}
                    {% endfor %}</td>-->
                    
                    <td>
                    {{stu.class_name}}
                    </td>
                    <td>
                    {{stu.class_category}}
                    </td>
                    <td>
                    {{stu}}
                    </td>
                    <td>
                    {% for c in stu.class_bkp_set.all %}
                    
                        {% if forloop.last %}
                            {{c.tches_name.first.tch_name}}
                        {% else %}
                            {{c..tches_name.first.tch_name}},
                        {% endif %}
                    {% endfor %}</td>
                    </td>
                    <td>
                    {{stu.stu_num}}
                    </td>
                    <td>
                    {{stu.class_count}}
                    </td>


                    <td>
                        <a href="{% url 'eduadmin' stu.pk %}" class="btn btn-default btn-sm">学员管理</a>
                        <a class="btn btn-default btn-sm roll" data-toggle="modal" data-target="#rollModal" roll_id="{{stu.pk}}">点名</a>
                        <a class="btn btn-warning btn-sm done" done_id="{{stu.pk}}">结业</a>
                        <a class="btn btn-danger btn-sm del" delete_id="{{stu.pk}}">删除</a>
                    </td>
                </tr>
                <nav aria-label="Page navigation"></nav>
            {% endfor %}
        </tbody>
    </table>
    <div class="col-md-8 col-md-offset-3">
    {{page_obj.page_html|safe}}
    </div>

    <!-- Button trigger modal -->


<!--roll Modal -->
<div class="modal fade rollModal" id="rollModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">签到册</h4>
      </div>
      <div class="modal-body" >
        <table class="table table-hover table-striped table-bordered " >
            
            <tr id="roll-table">
                <th>姓名</th>
                <th>账号</th>
                <th>签到</th>
            </tr>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submit_roll">提交</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
    $('#rollModal').on('hidden.bs.modal', function (e) {
  // do something...
})
    $('.del').on('click', function(){
        //this可以直接获取当前操作的对象
        let currentBtn = $(this);
        //弹出二次确认的弹框
        swal({
        title: "确定删除？",
        text: "删除后将不可恢复数据！",
        type: "warning",
        showCancelButton: true,
        confirmButtonClass: "btn-danger",
        confirmButtonText: "继续",
        cancelButtonText: "取消",
        closeOnConfirm: false,
        closeOnCancel: false
        },
        function(isConfirm) {
        if (isConfirm) {
            // 向后端发送ajax请求删除数据
            $.ajax({
                url:'/eduadmin/class/done/',
                type: 'POST',
                data:{'delete_id':currentBtn.attr('delete_id')},
                success: function(args){
                    // 判断响应状态码，做不同处理
                    if(args.code === 1000){
                    // 弹窗，删除成功
                    swal("删除成功!", args.msg, "success");
                    // 局部刷新
                    // 利用DOM 动态刷新
                    currentBtn.parent().parent().remove();

                    }
                
                else{
                    swal("失败!", "无法删除", "info")
                }}
            })
        }
        else {
            swal("已取消", "信息已安全保留 :)", "error");
        }
        });
    })

    $(".done").on("click",function(){
        //this可以直接获取当前操作的对象
        let currentBtn = $(this);
        //弹出二次确认的弹框
        swal({
        title: "确定结业？",
        text: "结业后将不可更改状态！",
        type: "warning",
        showCancelButton: true,
        confirmButtonClass: "btn-danger",
        confirmButtonText: "继续",
        cancelButtonText: "取消",
        closeOnConfirm: false,
        closeOnCancel: false
        },
        function(isConfirm) {
        if (isConfirm) {
            // 向后端发送ajax请求删除数据
            $.ajax({
                url:'/eduadmin/class/done/',
                type: 'POST',
                data:{
                    'done_id':currentBtn.attr('done_id'),
                    'csrfmiddlewaretoken':"{{csrf_token}}",
                    },
                success: function(args){
                    console.log(args.code)
                    // 判断响应状态码，做不同处理
                    if(args.code === 1000){
                    // 弹窗，删除成功
                    swal(args.msg,"更新成功!", "success");
                    // 局部刷新
                    // 利用DOM 动态刷新
                    //currentBtn.parent().parent().remove();

                    }
                
                else{
                    swal("失败!", "无法更新", "info")
                }}
            })
        }
        else {
            swal("已取消", "信息已安全保留 :)", "error");
        }
        });
    })

 
    $(".roll").on("click",function(){
        let currentBtn = $(this)
        let roll_id = currentBtn.attr("roll_id")
        $.ajax({
            url:"/eduadmin/class/roll/"+roll_id+"/",
            type:"GET",
            success: function(args){
                if (args.code === 1000){
                    console.log(args.roll_obj)
                    if (args.roll_obj){
                        for (var i of args.roll_obj ){
                            // 只能用在div上
                            //console.log($("#roll-table").children)
                            var roll_tr = $("#roll-table").after("<tr></tr>").next();
                            var roll_td = roll_tr.append("<td></td>").find("td");
                            var roll_account_td = roll_td.after("<td></td>").next();
                            var in_td = roll_account_td.after("<td><input type='checkbox' class='roll_stu_mode'></td>").next();
                            roll_tr.attr({"roll_stu_id":i.class_bkp__pk})
                            roll_td.attr({"roll_stu_id":i.class_bkp__pk})
                            in_td.attr({"id":i.class_bkp__pk,"class":"roll_stu_mode","value":i.class_bkp__pk})
                            roll_td.append(i.class_bkp__stu_detail__students__stu_name)
                            roll_account_td.append(i.class_bkp__stu_detail__students__stu_account)
    
                        }
                    }
                }
                else{
                    alert(args.msg)
                }
            }
        })
    })

    $('input[type=radio]').change(function() {
        if (this.id == 'done') {
            window.location.href="/eduadmin/class/filter/done/";
        }else if (this.id == 'doing') {
            window.location.href="/eduadmin/class/filter/doing/";
        }else if(this.id == 'none'){
          window.location.href="/eduadmin/class/filter/none/";
        }
        else{
            window.location.href="/eduadmin/class/admin/";
        }
     })

    $("#submit_roll").on('click', function(){
        // 签到学生id
        var checked = $("input[class='roll_stu_mode']:checked").parent()
        var checked_list = []
        for (i=0;i<checked.length;i++){
            checked_list.push(checked[i].id)
        }
        //弹出二次确认的弹框
        swal({
        title: "确定签到？",
        text: "签到后将不可更改！",
        type: "warning",
        showCancelButton: true,
        confirmButtonClass: "btn-danger",
        confirmButtonText: "继续",
        cancelButtonText: "取消",
        closeOnConfirm: false,
        closeOnCancel: false
        },
        function(isConfirm) {
        if (isConfirm) {
            // 向后端发送ajax请求删除数据
           $.ajax({
            url:"/eduadmin/class/roll/done/",
            type:"POST",
            data:{
                "csrfmiddlewaretoken":"{{csrf_token}}",
                "checked_list":JSON.stringify(checked_list),
            },
            success: function(args){
                    // 判断响应状态码，做不同处理
                    if(args.code === 1000){
                    // 弹窗，删除成功
                    swal("更新成功!", args.msg, "success");
                    }
                else if (args.code === 1001 ){
                    swal("未选择学员!", "请选择需签到的学员", "info")
                }
                else{
                    swal("失败!", "无法删除", "info")
                }
            }

        })}
        else {
            swal("已取消", "保持原课时数不变", "error");
        }
        });
    })
    
</script>
{% endblock %}

templates/errors.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <link rel="icon" href="//common.cnblogs.com/favicon.ico" type="image/x-icon" />
    <title>404 页面不存在 - CRO</title>
    <style type='text/css'>
        body {
            margin: 8% auto 0;
            max-width: 400px;
            min-height: 200px;
            padding: 10px;
            font-family: 'PingFang SC', 'Microsoft YaHei', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
            font-size: 14px;
            padding-right: 200px;
            position: relative;
        }
        p { color: #555;margin: 15px 0px; }
        img { border: 0px; }
        .d { color: #404040; }
        .robot img { max-width: 192px; }
        .robot { position: absolute; top: 0; right: 0; }
    </style>
</head>
<body>
    <!-- 图片防盗链-->
    <!-- 判断是否是本网站的请求，不是则自动拒绝-->
    <!-- 请求头 referer-->
    <!--<p style="margin-left: 5px;"><a href="{% url 'chome' %}"><img src="//common.cnblogs.com/logo.svg" style="height:45px" alt="cnblogs"></a></p>-->
    <div style="margin-top:20px">
        <p style=""><b style="">404.</b> 抱歉，您访问的资源不存在。</p>
        <p class="d">可能是网址有误，或者对应的内容被删除，或者处于私有状态。</p>
        <p style="color:#777;">代码改变世界，联系邮箱 lemon_gao@163.com</p>
    </div>
    <p><a href='/home/'>返回网站首页</a></p>
    
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-4CQQXWHK3C');
    </script>
</body>
</html>

templates/stu_add.html
<!-- 继承模板 -->
{% extends 'home.html' %}



{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
    <h3 class="panel-title">添加学员</h3>
    </div>
</div>
<form action="#" method="post">
<p>学员姓名
    <input type="text" name="stu_name" class="form-control" >
</p>
<p>账号
    <input type="text" name="stu_account" class="form-control" >
</p>
<p>密码
    <input type="text" name="password" class="form-control" >
</p>
<p>联系方式
    <input type="text" name="tel" class="form-control" >
</p>
<p>就读学校
    <input type="text" name="school" class="form-control" >
</p>
<p>生日
    <input type="date" name="birthday" class="form-control" >
</p>
<p>地址
    <input type="text" name="addr" class="form-control" >
</p>
<p>班级
    <select name="stu_class" id="" class="form-control">
        {% for obj in class_list %}
            <option value="{{obj.pk}}" multiple>{{obj.class_name}}</option>
        {% endfor %}
    </select>
</p>
<p>带班老师
    <select name="stu_teacher" id="" class="form-control">
        {% for obj in teacher_list %}
            <option value="{{obj.pk}}" multiple>{{obj.tch_name}}</option>
        {% endfor %}
    </select>
</p>
<input type="submit" value="新增" class="btn btn-primary btn-block">
</form>
{% endblock %}